[PHP]
variables_order = EGPCS
memory_limit = 4096M
max_execution_time = 90
max_input_time = 90
upload_max_filesize = 100M
post_max_size = 100M

[xdebug]
; Off until "lpod my-app xdebug on" or "lpod my-app debug" sets XDEBUG_MODE
xdebug.mode = off
xdebug.start_with_request = trigger
xdebug.client_host = host.containers.internal

[opcache]
opcache.enable = 0
opcache.enable_cli = 0
